// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxZ1Gy7hGmgPXymT0Mn7WscfHEtlRXZf8',
    appId: '1:947038821851:web:7885a6ba7a52ec1f74dbfe',
    messagingSenderId: '947038821851',
    projectId: 'bookswap-rw',
    authDomain: 'bookswap-rw.firebaseapp.com',
    storageBucket: 'bookswap-rw.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTcopRluJDo7927zRaW_lSeVqM1DSrtaA',
    appId: '1:947038821851:android:7ecd2b7d324d1e1174dbfe',
    messagingSenderId: '947038821851',
    projectId: 'bookswap-rw',
    storageBucket: 'bookswap-rw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHDj8mKhuz-AC7ID3trzNu6ej13y4Pw8s',
    appId: '1:947038821851:ios:5b9d03f11dae542374dbfe',
    messagingSenderId: '947038821851',
    projectId: 'bookswap-rw',
    storageBucket: 'bookswap-rw.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHDj8mKhuz-AC7ID3trzNu6ej13y4Pw8s',
    appId: '1:947038821851:ios:5b9d03f11dae542374dbfe',
    messagingSenderId: '947038821851',
    projectId: 'bookswap-rw',
    storageBucket: 'bookswap-rw.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxZ1Gy7hGmgPXymT0Mn7WscfHEtlRXZf8',
    appId: '1:947038821851:web:4f3d86cdfaa32ecd74dbfe',
    messagingSenderId: '947038821851',
    projectId: 'bookswap-rw',
    authDomain: 'bookswap-rw.firebaseapp.com',
    storageBucket: 'bookswap-rw.firebasestorage.app',
  );

}